'use client';
import {useEffect,useState} from 'react';
import './gameboy-intro.css';
const glyphs=['10000/10000/10110/11001/10001/10001/10001','00000/00000/01110/10001/11111/10000/01111','01100/00100/00100/00100/00100/00100/01110','01100/00100/00100/00100/00100/00100/01110','00000/00000/01110/10001/10001/10001/01110'];
export default function GameBoyIntro({onDone}:{onDone:()=>void}){
 const [phase,setPhase]=useState('hello');const [progress,setProgress]=useState(0);
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const start=performance.now();const tick=setInterval(()=>{const ms=performance.now()-start;const hello=reduced?650:1800;const vanish=reduced?0:400;const loading=1500;const end=hello+vanish+loading;if(ms<hello)setPhase('hello');else if(ms<hello+vanish)setPhase('vanish');else if(ms<end){setPhase('loading');setProgress(Math.min(100,Math.floor((ms-hello-vanish)/loading*20)*5))}else if(ms<end+450){setProgress(100);setPhase('ready')}else if(ms<end+900)setPhase('exit');else{clearInterval(tick);onDone()}},50);return()=>clearInterval(tick)},[onDone]);
 return <div className={'gb-intro phase-'+phase} role="dialog" aria-modal="true" aria-label="Game Boy 开机动画"><div className="gb-machine"><div className="gb-ridge"/><div className="gb-bezel"><div className="gb-bezel-top"><i/>DOT MATRIX WITH STEREO SOUND<i/></div><div className="gb-battery"><b/>BATTERY</div><div className="gb-lcd"><div className="gb-screen-caption">RICKY / PERSONAL ARCHIVE</div>{(phase==='hello'||phase==='vanish')&&<div className="gb-hello" aria-label="hello">{glyphs.map((g,i)=><svg key={i} viewBox="0 0 5 7" aria-hidden="true" style={{animationDelay:`${i*100}ms`}}>{g.split('/').flatMap((r,y)=>[...r].map((v,x)=>v==='1'?<rect key={`${x}-${y}`} x={x} y={y} width=".88" height=".88"/>:null))}</svg>)}</div>}{['loading','ready','exit'].includes(phase)&&<div className="gb-loading"><p>{progress===100?'READY!':'LOADING...'}</p><div className="gb-progress" role="progressbar" aria-label="开场过渡进度" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}>{Array.from({length:20},(_,i)=><i key={i} className={i<progress/5?'filled':''}/>)}</div><span>{progress}%</span></div>}<div className="gb-screen-footer">LEVEL DESIGNER <span>© RICKY</span></div></div></div><div className="gb-wordmark">Ricky <strong>GAME BOY</strong><sup>™</sup></div><div className="gb-controls" aria-hidden="true"><div className="gb-cross">✚</div><div className="gb-ab"><span>B</span><span>A</span></div></div><div className="gb-lower"><span>▰<small>SELECT</small></span><span>▰<small>START</small></span><div className="gb-speaker">╱╱╱╱╱</div></div></div><button className="gb-skip" onClick={onDone}>跳过开场 →</button><span className="gb-intro-label">A NEW CHAPTER / PRESS START</span></div>
}
