'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
const chapters = [
 {name:'起点',en:'THE SPAWN POINT',date:'PLAYER PROFILE',title:'你好，我是刘博 Ricky。',intro:'一名专注射击游戏的关卡策划。',body:'3 年以上游戏行业经验。从地图白盒、路线组织到交战空间，关注每一个设计选择如何影响玩家体验。',tags:['关卡策划','射击游戏','空间与玩法'],x:20,y:72},
 {name:'龙图游戏',en:'FIRST DEPLOYMENT',date:'2021.04 — 2021.12',title:'从白盒开始，建立战场。',intro:'龙图游戏 · 关卡策划',body:'参与 TPS 大逃杀手游项目，负责地图白盒、据点设计和资源配置。',tags:['TPS','大逃杀','据点设计'],x:36,y:49},
 {name:'网易游戏',en:'THE MAIN MISSION',date:'2021.12 — 2024.09',title:'让空间，产生战术。',intro:'网易游戏 · 关卡策划',body:'参与 5v5 英雄技能战术射击手游项目，独立设计完整爆破地图与 TDM 地图。负责地图优化、碰撞与掩体规范、局内武器穿射掩体系统，以及节日玩法模式设计。',tags:['爆破地图','TDM','玩法与规范'],x:56,y:62},
 {name:'新的探索',en:'SIDE QUESTS',date:'2024.09 — 至今',title:'换一张地图，继续探索。',intro:'创业实践 · AI 工具应用',body:'因家庭原因暂时离开游戏行业，开展个人创业实践。研究 AI Agent 与自动化，将新工具应用于实际业务流程。',tags:['AI Agent','自动化','持续学习'],x:69,y:35},
 {name:'下一张地图',en:'NEXT CHECKPOINT',date:'THE NEXT CHAPTER',title:'下一场，回到游戏。',intro:'关注射击游戏关卡策划机会',body:'带着已有的关卡设计经验与新的工具探索，寻找下一段射击游戏研发旅程。',tags:['射击游戏','关卡设计','新的旅程'],x:84,y:47}
];
function Block({x,y,w=65,d=42,h=38,color='#e2e6d8'}:{x:number;y:number;w?:number;d?:number;h?:number;color?:string}){return <g><path d={`M${x} ${y}l${w} ${w*.5}l${d} ${-d*.5}l${-w} ${-w*.5}Z`} fill={color}/><path d={`M${x} ${y}v${h}l${w} ${w*.5}v${-h}Z`} fill="#b5c5b2"/><path d={`M${x+w} ${y+w*.5}l${d} ${-d*.5}v${h}l${-d} ${d*.5}Z`} fill="#91ab9b"/><path d={`M${x} ${y}l${w} ${w*.5}l${d} ${-d*.5}l${-w} ${-w*.5}Z`} fill="none" stroke="#f8faf0" strokeWidth="1.5"/></g>}
function World(){return <svg className="world-svg" viewBox="0 0 1000 650" aria-hidden="true"><defs><pattern id="worldgrid" width="42" height="24" patternUnits="userSpaceOnUse"><path d="M0 12L21 0L42 12L21 24Z" fill="none" stroke="#92ae9a" strokeOpacity=".18"/></pattern><filter id="shadow"><feGaussianBlur stdDeviation="12"/></filter></defs><ellipse cx="526" cy="501" rx="350" ry="85" fill="#536f57" opacity=".13" filter="url(#shadow)"/><path d="M95 368L538 129L922 322V370L488 615L95 415Z" fill="#bcc9b3"/><path d="M95 368L488 567L922 322V370L488 615V567L95 415Z" fill="#a2b49e"/><path d="M95 368L538 129L922 322L488 567Z" fill="#e5e9d6" stroke="#f9faef" strokeWidth="3"/><path d="M95 368L538 129L922 322L488 567Z" fill="url(#worldgrid)"/>
<path d="M190 459L295 401L358 322L427 349L560 403L636 353L690 228L840 306" stroke="#f8f9ec" strokeWidth="20" fill="none" strokeLinejoin="round"/><path d="M190 459L295 401L358 322L427 349L560 403L636 353L690 228L840 306" stroke="#b99162" strokeWidth="2" fill="none" strokeDasharray="5 8"/>
<Block x={200} y={345} w={75} d={55} h={46}/><Block x={285} y={280} w={54} d={44} h={76}/><Block x={354} y={259} w={35} d={30} h={43}/><Block x={413} y={358} w={74} d={48} h={55}/><Block x={477} y={272} w={95} d={52} h={78}/><Block x={579} y={322} w={38} d={30} h={36}/><Block x={588} y={198} w={66} d={50} h={48}/><Block x={721} y={235} w={60} d={38} h={30}/><Block x={732} y={340} w={57} d={42} h={43}/><Block x={396} y={453} w={50} d={30} h={20}/>
{[[175,389],[329,408],[465,223],[641,414],[822,338],[569,463],[750,292]].map(([x,y],i)=><g key={i}><path d={`M${x} ${y}v-26`} stroke="#84947a" strokeWidth="4"/><path d={`M${x-13} ${y-15}L${x} ${y-55}L${x+14} ${y-15}Z`} fill="#809e7e"/><path d={`M${x} ${y-55}L${x+14} ${y-15}L${x} ${y-10}Z`} fill="#6c8f70"/></g>)}
<g fill="none" stroke="#fffdf0" strokeWidth="2"><path d="M515 343l42-23 42 23-42 23Z"/><path d="M505 342l52-29 52 29"/></g><g fontFamily="monospace" fontSize="10" fill="#788d75" letterSpacing="3"><text x="155" y="562">SECTOR 01 — CAREER ARCHIPELAGO</text><text x="755" y="176">N ↑</text></g></svg>}
export default function Journey(){const [started,setStarted]=useState(false);const [active,setActive]=useState(0);const [visited,setVisited]=useState<number[]>([]);const heading=useRef<HTMLHeadingElement>(null);const chapter=chapters[active];
function select(i:number){setActive(i);setVisited(v=>v.includes(i)?v:[...v,i]);}
useEffect(()=>{if(started)heading.current?.focus();},[started,active]);
return <div className={'game-shell '+(started?'is-playing':'is-title')}><div className="game-topline"><span><i/> RICKY / A LEVEL DESIGNER’S JOURNEY</span><span>INTERACTIVE PORTFOLIO <b>·</b> VOL. 01</span></div><div className="game-stage"><div className="world"><World/>{started&&chapters.map((c,i)=><button key={c.name} className={'world-node '+(active===i?'active':'')+' '+(visited.includes(i)?'visited':'')} style={{left:c.x+'%',top:c.y+'%'}} onClick={()=>select(i)} aria-label={`章节 ${i+1}：${c.name}`} aria-pressed={active===i}><span>{visited.includes(i)&&active!==i?'✓':`0${i+1}`}</span><small>{c.name}</small></button>)}<span className="world-caption">可探索的职业地图 / 非实际项目关卡</span></div>
{!started?<section className="title-screen"><p className="game-kicker">PRESS START TO EXPLORE</p><h1>每一张地图，<br/>都是一段<span>新的旅程。</span></h1><p className="player-name">刘博 <strong>Ricky</strong><span>关卡策划 / LEVEL DESIGNER</span></p><p className="title-desc">从第一块白盒，到下一片战场。<br/>沿着这条路线，认识我的设计与经历。</p><button className="start-button" onClick={()=>{setStarted(true);select(0);}}><span>▶</span> START <small>开始探索</small><span>↗</span></button><Link className="skip-link" href="/work">直接查看作品 <span>→</span></Link><div className="title-footnote"><span>05 个职业节点</span><b>·</b><span>自由切换，无需解锁</span></div></section>:<section className="mission-panel" aria-label="当前章节"><div className="mission-top"><span>CHAPTER 0{active+1}</span><button onClick={()=>setStarted(false)} aria-label="返回开始画面">✕</button></div><div key={active} className="mission-body"><p className="game-kicker">{chapter.en}</p><p className="mission-date">{chapter.date}</p><h1 ref={heading} tabIndex={-1}>{chapter.title}</h1><h2>{chapter.intro}</h2><p className="mission-description">{chapter.body}</p><div className="mission-tags">{chapter.tags.map(t=><span key={t}>{t}</span>)}</div>{active===2&&<div className="mission-file"><span>▧ 地图作品档案</span><p>爆破 / TDM 地图案例待补充。<br/>后续在这里打开设计过程、地图图片与迭代记录。</p><Link href="/work">进入作品区 ↗</Link></div>}{active===3&&<Link className="mission-link" href="/lab">进入 AI 探索支线 ↗</Link>}{active===4&&<div className="mission-file"><p>联系方式与简历待补充。</p><Link href="/about">查看完整经历 ↗</Link></div>}</div><div className="mission-controls"><button disabled={active===0} onClick={()=>select(active-1)}>← 上一站</button>{active<4?<button className="next-mission" onClick={()=>select(active+1)}>继续探索 <span>→</span></button>:<button className="next-mission" onClick={()=>{setStarted(false);}}>返回标题 ↗</button>}</div></section>}
</div>{started?<div className="journey-hud"><div className="hud-progress"><span>EXPLORATION</span><strong>{visited.length} / 05</strong><progress value={visited.length} max={5} aria-label="已查看章节"/></div><nav aria-label="职业章节">{chapters.map((c,i)=><button key={c.name} onClick={()=>select(i)} aria-current={active===i?'step':undefined}><span>0{i+1}</span>{c.name}{visited.includes(i)&&<i/>}</button>)}</nav><Link href="/blog" className="journal-link">▤ 设计随笔 ↗</Link></div>:<div className="game-bottom"><span>DESIGNED SPACES. MEANINGFUL CHOICES.</span><span>空间布局 <b>＋</b> 交战节奏 <b>＋</b> 玩家决策</span><span>EST. 2021</span></div>}</div>}
