'use client';
import SiteAnchor from './SiteAnchor';
import {useEffect,useRef,useState,useCallback} from 'react';
import Link from 'next/link';
import {Badge} from './Arcade';
import GameBoyIntro from './GameBoyIntro';
import {career} from '../content/career';
import './reference-flow.css';
const clamp=(v:number)=>Math.min(1,Math.max(0,v));
const projectRows=[['虚灵遗迹 · 原创爆破地图','LEVEL DESIGN / COMPLETE MAP','/work/ethereal-ruins'],['既有地图 · Gameplay 优化','LEVEL DESIGN / DIAGNOSIS','/work/gameplay-polish'],['圣诞打雪仗 · 上线交付','GAME MODE / DELIVERY','/work/christmas-snowball'],['穿射 · 规则与空间反馈','SYSTEMS / LEVEL DESIGN','/work/penetration-system'],['龙图 · 大逃杀据点与建筑','LEVEL DESIGN / BATTLE ROYALE','/work/longtu-battle-royale']];
function Landscape({night=false}:{night?:boolean}){return <svg className={'flow-landscape '+(night?'night':'')} viewBox="0 0 1400 430" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id={night?'grass-night':'grass-day'} x2="0" y2="1"><stop stopColor={night?'#738a70':'#95ad72'}/><stop offset="1" stopColor={night?'#263d37':'#456951'}/></linearGradient></defs><path d="M0 260Q140 160 330 240Q520 80 705 120Q900 158 1040 230Q1220 136 1400 193V430H0Z" fill={night?'#344b43':'#77997b'}/><path d="M0 340Q200 295 386 255Q623 98 788 152Q967 239 1120 273Q1290 250 1400 330V430H0Z" fill={`url(#${night?'grass-night':'grass-day'})`}/>{Array.from({length:270},(_,i)=>{const x=((Math.sin(i*127.1+3)*43758.5453)%1+1)%1*1400;const y=245+(((Math.sin(i*311.7+7)*19341.93)%1+1)%1)*185;const col=['#f4e6c7','#efc9bc','#c7c7dd','#c4d293'][i%4];return <g key={i} opacity={.35+(i%4)*.16}><path d={`M${x} ${y+9}l-2 -14m2 14 4-9`} stroke={night?'#6f8a65':'#b4c78c'} strokeWidth="1.2"/>{i%3===0&&<circle cx={x-2} cy={y-6} r={2+i%3} fill={col}/>}</g>})}</svg>}
function Portrait(){return <div className="portrait-slot"><div className="portrait-rise" aria-hidden="true"><span>R</span><i>✎</i></div><div className="portrait-frame"><div><span>R</span><small>LEVEL<br/>DESIGNER</small></div><p>Ricky / 刘博</p></div><small className="portrait-hint">刘博 / 关卡策划</small></div>}
function PhoneBooth({open,onToggle}:{open:boolean;onToggle:()=>void}){return <button className={'phone-booth '+(open?'phone-open':'')} onClick={onToggle} aria-label="打开或关闭电话亭" aria-expanded={open}><span className="booth-roof">♜</span><span className="booth-label">TELEPHONE</span><span className="booth-side"/><span className="booth-interior"><span>☎</span><i/></span><span className="booth-door"><span className="booth-glass"/><i/></span><span className="booth-base"/></button>}
export default function ReferenceFlow(){const [boot,setBoot]=useState(true);const [reduced,setReduced]=useState(false);const [paused,setPaused]=useState(false);const [selected,setSelected]=useState(1);const [preview,setPreview]=useState<number|null>(null);const [phone,setPhone]=useState(false);const [mail,setMail]=useState(false);const [active,setActive]=useState('home');const hero=useRef<HTMLElement>(null);const previewRef=useRef<HTMLDivElement>(null);
 const finishBoot=useCallback(()=>setBoot(false),[]);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(q.matches);sync();q.addEventListener('change',sync);return()=>q.removeEventListener('change',sync)},[]);
 useEffect(()=>{if(!boot)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[boot]);
 const go=(section:string)=>{setBoot(false);setActive(section);document.getElementById(section==='home'?'about':section)?.scrollIntoView({behavior:reduced?'instant':'smooth'})};
 const about=1;
 return <div className={'reference-flow '+(reduced?'flow-reduced':'')}>
{boot&&<GameBoyIntro onDone={finishBoot}/>}
<div inert={boot}><header className="flow-nav"><SiteAnchor href="#home" onClick={e=>{e.preventDefault();go('home')}} className="flow-logo">RICKY<span>刘博 / LEVEL DESIGNER</span></SiteAnchor><nav aria-label="页面导航">{[['home','Home'],['about','About'],['portfolio','Portfolio']].map(([id,name])=><SiteAnchor key={id} href={'#'+id} onClick={e=>{e.preventDefault();go(id)}} aria-current={active===id?'location':undefined}>{name}</SiteAnchor>)}<Link href="/work">全部作品</Link><Link href="/blog">设计随笔</Link><Link href="/lab">AI 探索</Link><SiteAnchor href="/resume/ricky-level-designer.pdf" download="刘博_关卡策划_简历.pdf">Resume · 下载简历</SiteAnchor><button className="flow-motion" onClick={()=>setPaused(v=>!v)} aria-label={paused?'恢复工牌摇晃':'暂停工牌摇晃'}>{paused?'▷':'Ⅱ'}</button></nav></header>
<section className="flow-hero" id="home" ref={hero} aria-label="个人博客"><div className="hero-sticky">
<section id="about" className="flow-about" style={{opacity:about,visibility:'visible',transform:`scale(${.94+about*.06})`}} inert={about<.95} aria-label="About 个人介绍"><div className="paper-dossier"><div className="dossier-left"><span className="dossier-index">PERSONNEL / 01—03</span><div className="comic-lines"/><div className="dossier-badges">{career.map((c,i)=><Badge key={c.id} item={c} moving={!paused&&!reduced&&about>.95} open={i===selected} onSelect={()=>setSelected(i)}/>)}</div><span className="badge-note">拖动工牌 · 点击定位经历<br/>个人经历设计稿，非原始证件</span></div><div className="dossier-main"><div className="dossier-heading"><h2>ABOUT ME</h2><span>DESIGNER NO. R-001<br/>▥ ▥▥▥ ▥</span></div><p className="dossier-subhead">LEVEL DESIGN / SYSTEMS / EXPERIMENTS</p><h3>HI! I’M RICKY</h3><p className="dossier-intro">刘博，3 年以上 FPS/TPS 关卡策划经验。<br/>从白盒到上线交付，专注战术空间与交战体验。</p><div className="experience-label">Experience</div><div className="experience-list">{career.map((c,i)=><button key={c.id} onClick={()=>setSelected(i)} className={i===selected?'experience-selected':''}><span><strong>{c.company} / {c.role}</strong><time>{c.period}</time></span><p>{c.details}</p></button>)}</div></div><div className="dossier-right"><Portrait/><div className="paper-ticket">LEVEL DESIGNER<br/><b>RICKY</b><span>▰ ▰▰ ▰ ▰</span><small>PERSONAL ARCHIVE</small></div></div></div></section></div></section>
<section className="flow-projects" id="portfolio" aria-label="作品列表"><p className="section-stamp">SELECTED PORTFOLIO / LEVEL DESIGN</p><div className="project-table" onPointerMove={e=>{if(previewRef.current){const r=e.currentTarget.getBoundingClientRect();previewRef.current.style.left=`${clamp((e.clientX-r.left)/r.width)*55+20}%`;previewRef.current.style.top=`${e.clientY-r.top}px`;}}} onPointerLeave={()=>setPreview(null)}>{projectRows.map(([name,en,url],i)=><Link href={url} key={name} className="project-row" onPointerEnter={()=>setPreview(i)} onFocus={()=>setPreview(i)} onBlur={()=>setPreview(null)}><span className="project-no">0{i+1}</span><span className="project-title"><strong>{name}</strong><small>{en}</small></span><span className="project-status">查看案例</span><span className="project-arrow">↗</span></Link>)}<div className={'project-hover '+(preview!==null?'shown':'')} ref={previewRef} aria-hidden="true"><div className="preview-grid"><span>0{(preview??0)+1}</span><i/><b>PROJECT FILE</b></div><p>{projectRows[preview??0][0]}</p><small>文字案例 / 非项目截图</small></div></div><nav className="content-links" aria-label="更多内容"><Link href="/work">全部作品 ↗</Link><Link href="/blog">设计随笔 ↗</Link><Link href="/lab">AI 与经营实践 ↗</Link><Link href="/about">个人资料与联系 ↗</Link></nav></section>
<section className="flow-contact" id="contact" aria-label="联系方式"><div className="contact-scenery"><Landscape night/><div className="contact-island"/><PhoneBooth open={phone} onToggle={()=>setPhone(v=>!v)}/><button className={'mailbox '+(mail?'mail-open':'')} onClick={()=>setMail(v=>!v)} aria-label="打开或关闭邮箱" aria-expanded={mail}><span className="mailbox-post"/><span className="mailbox-body"><span>MAIL</span></span><i/></button><div className="phone-annotation">Telephone <span>↙</span><small>点击电话亭</small></div><div className="mail-annotation">Email ✉ <span>↘</span><small>点击邮箱</small></div>{phone&&<div className="phone-reveal" role="status"><strong>LET’S TALK!</strong><p><SiteAnchor href="tel:17701055564">17701055564</SiteAnchor></p><small>关卡策划工作联系</small></div>}{mail&&<div className="mail-reveal" role="status"><span>✉</span><strong><SiteAnchor href="mailto:404291277@qq.com">404291277@qq.com</SiteAnchor></strong><small>欢迎通过邮件联系</small></div>}</div><div className="flow-end"><span>© RICKY / 刘博</span><button onClick={()=>go('home')}>BACK TO TOP ↑</button><span>LEVEL DESIGNER PORTFOLIO</span></div></section>
</div></div>}
