'use client';

import Link from 'next/link';
import {useCallback, useEffect, useState} from 'react';
import type {CSSProperties} from 'react';
import SiteAnchor from './SiteAnchor';
import {Badge} from './Arcade';
import GameBoyIntro from './GameBoyIntro';
import {career} from '../content/career';
import './reference-flow.css';

const projectGroups = [
  {no:'01',title:'关卡白盒',english:'LEVEL BLOCKOUT',summary:'原创爆破地图「虚灵遗迹」｜TDM 完整地图｜龙图大逃杀据点与通用建筑',note:'从 Layout、Whitebox 到美术落地，集中展示战术路线、交战空间与迭代过程。',href:'/work/ethereal-ruins',image:'/media/work/ruins-overview.webp',imageAlt:'虚灵遗迹白盒鸟瞰',tags:['虚灵遗迹','TDM','大逃杀据点']},
  {no:'02',title:'地图优化',english:'GAMEPLAY POLISH',summary:'既有地图 Gameplay 诊断｜热力图观察｜可读性、碰撞与技能通行',note:'从实际游玩问题出发，让画面、规则和交战空间保持一致。',href:'/work/gameplay-polish',image:'/media/work/polish-after.webp',imageAlt:'地图掩体结构调整后画面',tags:['空间诊断','地图迭代','可读性']},
  {no:'03',title:'活动模式',english:'LIMITED-TIME MODE',summary:'圣诞打雪仗｜规则、地图适配、投掷体验与完整上线交付',note:'在既有地图上完成玩法设计、跨专业跟进、跑测、验收与版本交付。',href:'/work/christmas-snowball',image:'/media/work/snow-overview.webp',imageAlt:'圣诞打雪仗场景总览',tags:['规则设计','地图适配','上线交付']},
  {no:'04',title:'系统与杂项',english:'SYSTEMS & SUPPORT',summary:'穿射规则与反馈｜训练场打靶评分｜地图维护与数据观察',note:'把系统规则转译为空间要求，并承担评分、反馈和地图维护类工作。',href:'/work/systems-iteration',image:'/media/work/penetration-layout.webp',imageAlt:'Layout 中的穿射设计标记',tags:['穿射系统','训练场评分','热力图']},
] as const;

function Landscape(){return <svg className="flow-landscape" viewBox="0 0 1400 430" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="contact-grass" x2="0" y2="1"><stop stopColor="#506b61"/><stop offset="1" stopColor="#152a29"/></linearGradient></defs><path d="M0 260Q140 160 330 240Q520 80 705 120Q900 158 1040 230Q1220 136 1400 193V430H0Z" fill="#304b47"/><path d="M0 340Q200 295 386 255Q623 98 788 152Q967 239 1120 273Q1290 250 1400 330V430H0Z" fill="url(#contact-grass)"/>{Array.from({length:150},(_,i)=>{const x=(i*137)%1400;const y=250+((i*83)%180);return <circle key={i} cx={x} cy={y} r={i%4===0?2.2:1.1} fill={['#e8d9b8','#d7b6aa','#aeb9c4','#aebc91'][i%4]} opacity={.35+(i%3)*.18}/>})}</svg>}
function PhoneBooth({open,onToggle}:{open:boolean;onToggle:()=>void}){return <button className={'phone-booth '+(open?'phone-open':'')} onClick={onToggle} aria-label="打开或关闭电话亭" aria-expanded={open}><span className="booth-roof">♜</span><span className="booth-label">TELEPHONE</span><span className="booth-interior"><span>☎</span></span><span className="booth-door"><span className="booth-glass"/><i/></span><span className="booth-base"/></button>}

export default function ReferenceFlow(){
  const [boot,setBoot]=useState(true); const [reduced,setReduced]=useState(false); const [paused,setPaused]=useState(false); const [selected,setSelected]=useState(1); const [preview,setPreview]=useState(0); const [phone,setPhone]=useState(false); const [mail,setMail]=useState(false); const [active,setActive]=useState<'home'|'about'|'portfolio'>('home');
  const finishBoot=useCallback(()=>{setBoot(false);setActive('about')},[]);
  useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(query.matches);sync();query.addEventListener('change',sync);return()=>query.removeEventListener('change',sync)},[]);
  useEffect(()=>{if(!boot)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[boot]);
  useEffect(()=>{if(boot)return;const sync=()=>{const portfolio=document.getElementById('portfolio');setActive(portfolio&&window.scrollY>=portfolio.offsetTop-window.innerHeight*.42?'portfolio':'about')};sync();window.addEventListener('scroll',sync,{passive:true});window.addEventListener('resize',sync);return()=>{window.removeEventListener('scroll',sync);window.removeEventListener('resize',sync)}},[boot]);
  const go=(section:'about'|'portfolio')=>{setBoot(false);setActive(section);document.getElementById(section)?.scrollIntoView({behavior:reduced?'auto':'smooth'})};
  const replay=()=>{window.scrollTo({top:0,behavior:'auto'});setActive('home');setBoot(true)};
  const current=career[selected];
  return <div className={'reference-flow '+(reduced?'flow-reduced':'')}>
    {boot&&<GameBoyIntro onDone={finishBoot}/>}<div inert={boot}>
      <header className="flow-nav"><button className="flow-logo" onClick={replay} aria-label="重播首页开场"><strong>RICKY</strong><span>刘博 / LEVEL DESIGNER</span></button><nav aria-label="页面导航"><SiteAnchor href="#home" onClick={e=>{e.preventDefault();replay()}} aria-current={active==='home'?'location':undefined}>Home</SiteAnchor><SiteAnchor href="#about" onClick={e=>{e.preventDefault();go('about')}} aria-current={active==='about'?'location':undefined}>About</SiteAnchor><SiteAnchor href="#portfolio" onClick={e=>{e.preventDefault();go('portfolio')}} aria-current={active==='portfolio'?'location':undefined}>Portfolio</SiteAnchor><SiteAnchor className="flow-resume" href="/resume/ricky-level-designer.pdf" download="刘博_关卡策划_简历.pdf">Resume Download <span>↓</span></SiteAnchor><button className="flow-motion" onClick={()=>setPaused(v=>!v)} aria-label={paused?'恢复工牌摇晃':'暂停工牌摇晃'}>{paused?'▷':'Ⅱ'}</button></nav></header>
      <div id="home">
        <section id="about" className="flow-about" aria-label="About 个人介绍"><div className="about-halo" aria-hidden="true"/><div className="paper-dossier">
          <div className="dossier-left"><span className="dossier-index">CAREER BADGES / 01—03</span><div className="comic-lines"/><div className="dossier-badges">{career.map((item,i)=><Badge key={item.id} item={item} moving={!paused&&!reduced} open={i===selected} onSelect={()=>setSelected(i)}/>)}</div><span className="badge-note">可拖动工牌 · 点击切换经历<br/>网易经历置于最前层</span></div>
          <div className="dossier-main"><div className="dossier-heading"><div><span>PERSONAL DOSSIER / 2026</span><h1>ABOUT ME</h1></div><b>R-001<br/>▥ ▥▥▥ ▥</b></div><p className="dossier-subhead">LEVEL DESIGN · FPS / TPS · SHOOTER GAMES</p><p className="dossier-hello">HI! I’M RICKY</p><h2>刘博，关卡策划。<br/><span>让空间产生战术。</span></h2><p className="dossier-intro">3 年以上 FPS / TPS 项目经验，负责过原创爆破地图、完整 TDM 地图、既有地图优化、活动模式与系统类功能。从白盒验证到上线验收，持续关注路线选择、交战节奏与空间可读性。</p><div className="selected-career" style={{'--career-color':current.color} as CSSProperties}><div><span>{current.label} / {current.code}</span><time>{current.period}</time></div><h3>{current.company}<small>{current.role}</small></h3><p>{current.details}</p><Link href={current.href}>{current.link} <span>↗</span></Link></div><div className="career-tabs" aria-label="切换工作经历">{career.map((item,i)=><button key={item.id} className={i===selected?'selected':''} onClick={()=>setSelected(i)}><span>0{i+1}</span>{item.company}</button>)}</div></div>
          <aside className="dossier-right"><div className="profile-polaroid"><div><img src={(process.env.NEXT_PUBLIC_BASE_PATH||'')+'/media/profile/netease-portrait.jpg'} alt="刘博个人照片"/></div><p>Ricky / 刘博</p><small>LEVEL DESIGNER</small></div><div className="paper-ticket"><span>MAIN CHAPTER</span><strong>NETEASE<br/>2021—2024</strong><p>《天启行动》<br/>原创爆破地图 · 玩法与系统</p><i>VERIFIED EXPERIENCE</i></div></aside>
        </div><button className="about-scroll" onClick={()=>go('portfolio')}><span>SCROLL TO PORTFOLIO</span><i>↓</i></button></section>
        <section className="flow-projects" id="portfolio" aria-label="作品分类"><div className="portfolio-watermark" aria-hidden="true">PORTFOLIO</div><header className="portfolio-head"><p>SELECTED WORK / 2021—2024</p><h2>按工作类型查看作品</h2><span>关卡白盒、地图优化、活动模式，以及系统与支持类工作。</span></header><div className="portfolio-layout"><div className="project-table" onPointerLeave={()=>setPreview(0)}>{projectGroups.map((group,i)=><Link href={group.href} key={group.no} className={'project-row '+(preview===i?'is-active':'')} onPointerEnter={()=>setPreview(i)} onFocus={()=>setPreview(i)}><span className="project-no">{group.no}</span><span className="project-title"><strong>{group.title}</strong><small>{group.english}</small><em>{group.summary}</em></span><span className="project-arrow">↗</span></Link>)}</div><div className="project-preview" aria-live="polite"><div className="preview-image"><img key={projectGroups[preview].image} src={(process.env.NEXT_PUBLIC_BASE_PATH||'')+projectGroups[preview].image} alt={projectGroups[preview].imageAlt}/><span>{projectGroups[preview].no}</span></div><p>{projectGroups[preview].note}</p><div>{projectGroups[preview].tags.map(tag=><span key={tag}>{tag}</span>)}</div><Link href={projectGroups[preview].href}>打开该板块 <span>↗</span></Link></div></div><nav className="content-links" aria-label="更多内容"><Link href="/work">全部作品</Link><Link href="/blog">设计随笔</Link><Link href="/lab">AI 探索</Link><Link href="/about">个人资料</Link></nav></section>
        <section className="flow-contact" id="contact" aria-label="联系方式"><div className="contact-scenery"><Landscape/><div className="contact-island"/><PhoneBooth open={phone} onToggle={()=>setPhone(v=>!v)}/><button className={'mailbox '+(mail?'mail-open':'')} onClick={()=>setMail(v=>!v)} aria-label="打开或关闭邮箱" aria-expanded={mail}><span className="mailbox-post"/><span className="mailbox-body">MAIL</span></button><div className="phone-annotation">Telephone <small>点击电话亭</small></div><div className="mail-annotation">Email ✉ <small>点击邮箱</small></div>{phone&&<div className="phone-reveal" role="status"><strong>LET’S TALK!</strong><p><SiteAnchor href="tel:17701055564">17701055564</SiteAnchor></p><small>关卡策划工作联系</small></div>}{mail&&<div className="mail-reveal" role="status"><span>✉</span><strong><SiteAnchor href="mailto:404291277@qq.com">404291277@qq.com</SiteAnchor></strong><small>欢迎通过邮件联系</small></div>}</div><div className="flow-end"><span>© RICKY / 刘博</span><button onClick={()=>go('about')}>BACK TO TOP ↑</button><span>LEVEL DESIGNER PORTFOLIO</span></div></section>
      </div>
    </div>
  </div>
}
