'use client';
import SiteAnchor from './SiteAnchor';
import {useState,type ReactNode} from 'react';
import {career} from '../content/career';
import './screen-portfolio.css';
type File={title:string;summary:string;slug:string;kind:string;body:ReactNode};
const tabs=['总览','地图与项目','工作经历','随笔与实践','联系'];
export default function ScreenPortfolio({files}:{files:File[]}){
 const [tab,setTab]=useState(0);const [file,setFile]=useState<number|null>(null);
 const select=(i:number)=>{setTab(i);setFile(null)};
 const open=(i:number)=>{setFile(i)};
 const list=(kind:string)=><div className="lcd-files">{files.map((f,i)=>f.kind===kind&&<button key={f.slug} onClick={()=>open(i)}><span className="lcd-file-code">{String(i+1).padStart(2,'0')} / {kind==='work'?'PROJECT':'JOURNAL'}</span><h3>{f.title}</h3><p>{f.summary}</p><span className="lcd-read">打开档案 ↗</span></button>)}</div>;
 return <div className="screen-site"><div className="console-shell"><div className="console-top"><span>RICKY <b>GAME BOY</b></span><span>PERSONAL PORTFOLIO / 2026</span><span className="power-label"><i/> POWER ON</span></div><div className="screen-bezel"><div className="bezel-label"><span>DOT MATRIX WITH STEREO SOUND</span><span>LEVEL DESIGN ARCHIVE</span></div><div className="portfolio-lcd"><header className="lcd-status"><SiteAnchor href="/" aria-label="返回首页">R / 刘博</SiteAnchor><span>LEVEL DESIGNER</span><SiteAnchor href="/resume/ricky-level-designer.pdf" download="刘博_关卡策划_简历.pdf">↓ 简历 PDF</SiteAnchor></header><nav className="lcd-tabs" aria-label="屏幕栏目">{tabs.map((t,i)=><button key={t} onClick={()=>select(i)} aria-current={tab===i&&file===null?'page':undefined}><small>0{i+1}</small>{t}</button>)}</nav><main className="lcd-content" key={file===null?`tab-${tab}`:`file-${file}`}>
 {file!==null?<article className="lcd-article"><button className="lcd-back" onClick={()=>setFile(null)}>← 返回{tabs[tab]}</button><p className="lcd-kicker">ARCHIVE / {files[file].kind.toUpperCase()}</p><h1>{files[file].title}</h1><p className="lcd-deck">{files[file].summary}</p><div className="prose">{files[file].body}</div></article>:<>
 {tab===0&&<><div className="lcd-hero"><div><p className="lcd-kicker">PLAYER 01 / READY TO DESIGN</p><h1>刘博 <span>Ricky</span></h1><h2>关卡策划 / Level Designer</h2><p className="lcd-deck">让空间产生战术，<br/>让设计落地成可玩的关卡。</p><p className="lcd-summary">3 年以上 FPS/TPS 关卡策划经验。参与网易《天启行动》与龙图大逃杀研发，覆盖概念、Layout、白盒、测试迭代、美术落地及上线验收。</p><div className="lcd-actions"><button onClick={()=>select(1)}>▶ 浏览地图档案</button><button onClick={()=>select(2)}>查看完整经历 →</button></div></div><aside className="lcd-feature"><span className="lcd-kicker">FEATURED / 网易游戏</span><div className="lcd-map" aria-hidden="true"><span>A</span><i/><b>B</b><small>LEVEL DESIGN / ARCHIVE</small></div><p className="lcd-map-caption">界面装饰 · 非项目地图</p><h3>虚灵遗迹</h3><p>原创爆破地图 · 公测上线<br/>从概念到上线交付的完整负责经历</p><button onClick={()=>open(files.findIndex(f=>f.slug==='ethereal-ruins'))}>打开代表项目 ↗</button></aside></div><div className="lcd-facts"><div><small>01 / MAPS</small><strong>爆破 · TDM · 大逃杀</strong><p>整图白盒、战术空间与可复用建筑</p></div><div><small>02 / DELIVERY</small><strong>设计 → 制作 → 上线</strong><p>圣诞雪球活动及地图相关 Feature</p></div><div><small>03 / EXPERIENCE</small><strong>网易 / 龙图 / 韩国读研</strong><p>游戏设计进修与 AI 辅助工作流学习</p></div></div><div className="lcd-education">韩国祥明大学 · 游戏设计本科 <span>2017.03 — 2021.02</span></div></>}
 {tab===1&&<><p className="lcd-kicker">SELECTED WORK / 05 FILES</p><h1>地图与项目</h1><p className="lcd-deck">从战术空间到完整交付。点击档案，在屏幕内阅读。</p>{list('work')}</>}
 {tab===2&&<><p className="lcd-kicker">CAREER LOG</p><h1>工作经历</h1><div className="lcd-career">{[career[1],career[0],career[2]].map(c=><section key={c.id}><span>{c.period}</span><h2>{c.company} <small>{c.role}</small></h2><p>{c.details}</p></section>)}</div><p className="lcd-education">韩国祥明大学 · Game Design / 游戏设计 · 本科 · 2017.03—2021.02</p></>}
 {tab===3&&<><p className="lcd-kicker">DESIGN NOTES / TOOL PRACTICE</p><h1>随笔与实践</h1><p className="lcd-deck">具体工作方法，以及游戏研发之外的持续探索。</p>{list('blog')}{list('lab')}</>}
 {tab===4&&<><p className="lcd-kicker">CONNECT / NEXT CHAPTER</p><h1>一起讨论下一张地图。</h1><p className="lcd-deck">关注射击游戏关卡策划机会，欢迎通过电话或邮件联系。</p><div className="lcd-contact"><SiteAnchor href="tel:17701055564"><small>PHONE</small>17701055564 ↗</SiteAnchor><SiteAnchor href="mailto:404291277@qq.com"><small>EMAIL</small>404291277@qq.com ↗</SiteAnchor><SiteAnchor href="/resume/ricky-level-designer.pdf" download="刘博_关卡策划_简历.pdf"><small>RESUME / A4 · 1 PAGE</small>下载完整简历 ↓</SiteAnchor></div></>}
 </>}
 </main><footer className="lcd-footer"><span>刘博 / RICKY — 关卡策划</span><span>{file===null?`MENU 0${tab+1}`:'READING FILE'} ▪</span></footer></div></div><div className="console-bottom"><span className="console-brand">Ricky <b>GAME BOY</b><small>PORTFOLIO EDITION</small></span><div className="console-controls"><button onClick={()=>select((tab+tabs.length-1)%tabs.length)} aria-label="上一栏目">◀</button><button onClick={()=>select((tab+1)%tabs.length)} aria-label="下一栏目">▶</button><button className="console-b" onClick={()=>file!==null?setFile(null):select(0)} aria-label="返回总览或列表">B</button><button className="console-a" onClick={()=>select(1)} aria-label="打开项目列表">A</button></div><div className="console-speaker" aria-hidden="true">▰ ▰ ▰ ▰ ▰</div></div></div></div>
}
